#!/usr/bin/env bash
#
# Script name: nvidia-launcher
# Description: 
# Dependencies: nvidia proprieatry drivers
# Github: https://www.github.com/appcreatorguy/dotfiles
# Licence: https://www.github.com/appcreatorguy/dotfiles/LICENSE
# Contributors: Manas Mengle

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing. Otherwise we can
# get hidden bugs that are hard to discover
# set -eou pipefail

__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
