# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$character"""

# Inserts a blank line between shell prompts
add_newline = false


[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold green)"
